site_name: PEOPLE-ER Wetland Function Assessment Tutorial

nav:
- Home: index.md
- Notebook pages: 
    - 'Notebook pages/1. 01_inspect_S1_time_series.ipynb'
    - 'Notebook pages/2. 02_landscape_segmentation.ipynb'
    - 'Notebook pages/3. 03_compile_time_series.ipynb'
    - 'Notebook pages/4. 04_cluster_analysis.ipynb'
    - 'Notebook pages/5. 05_calculate_dtw.ipynb'

plugins:
  - mkdocs-jupyter:
      include_source: True
